logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  security:
    oauth2:
      client:
        registration:
          mock:
            client-id: test
            client-secret: secret
            scopes: read
            authorization-grant-type: client_credentials
        provider:
          mock:
            token-uri: ${mockwebserver.url}/oauth/token

