logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  security:
    oauth2:
      client:
        registration:
            mock:
            client-id: test-id
            client-secret: secret
            provider: mock
            scopes: read
        provider:
          mock:
